### PR TITLE
fix for https://github.com/serenity-bdd/serenity-core/issues/924

### PR DESCRIPTION
**Pull request by cliviu**
Hi, I have searched a lot to try to understand the problems that we have and I have found out this fix. The check (if (testState.currentStep != null) {) is also done in beforeStory/afterStory.Adding it also in succesful() fixes our issue.

### CODE REVIEW

**Review by valfirst — APPROVED** [review]

**Comment by cliviu** [comment]
Thanks  a lot, when is the new version release planned ?

**Comment by valfirst** [comment]
@cliviu, I plan to release next weekend

**Comment by cliviu** [comment]
Thanks !

**Comment by valfirst** [comment]
@cliviu, the new version is released:
```xml
<dependency>
    <groupId>com.github.valfirst</groupId>
    <artifactId>jbehave-junit-runner</artifactId>
    <version>2.1.0</version>
</dependency>
```

**Pull request merged**
