### PR TITLE
Add support of multithreaded story execution. Upgrade to JBehave 4.1.1

### PR DESCRIPTION
**Pull request by valfirst**
Implementation of https://github.com/codecentric/jbehave-junit-runner/issues/20

### CODE REVIEW

**Comment by valfirst** [comment]
@AndreasEK , @joshiste, does anybody support this project?

**Comment by valfirst** [comment]
@britter, maybe you know the future of this project?

**Comment by britter** [comment]
@valfirst sorry, I don't. I'll reach out to some guys who maintained it in the past. Maybe we can just transfer ownership.

**Comment by valfirst** [comment]
@britter, thank you! looking forward for updates. I'm really sorry inconvenience, but it looks like you are the only one who really cares

**Comment by britter** [comment]
@valfirst I talked to the people who have been working on this project in the past and they don't have the time to maintain it any more. Would you be willing to maintain this project? Then we are willing to transfer ownership of this repository to you. Since the artifacts are currently distributed under de.codecentric Group ID you will probably have to change those coordinates.

**Comment by valfirst** [comment]
@britter, yes, I would like to maintain this project. And I'm absolutely fine with group ID change. What's required from my side?

**Comment by britter** [comment]
@valfirst you need to delete your fork of this repository. Otherwise I cannot transfer it, because there can be only one repository of this name in your account.

**Comment by valfirst** [comment]
@britter I've renamed the fork. would it be enough?

**Comment by britter** [comment]
@valfirst still not possible. I get this error message:

> valfirst already has a repository in the avh4/jbehave-junit-monitor network and You can only transfer a repository from an organization to yourself at this time

**Comment by valfirst** [comment]
@britter I've completely removed the fork, could you please try again? thanks

**Comment by valfirst** [comment]
@britter it looks like transfer was successful, thank you very much for your help!

**Comment by britter** [comment]
Take good care of this code! :-)

**Pull request merged**
